# -*- coding: utf-8 -*-
"""00_HelloWord.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fvegBiWHBE8-8p4IC8_A2UPWkb5LmHNA
"""

# Este simbolo se utiliza para comentar el codigo.
print("Hola grupo 230 de la carrera tecnica de PROGRAMACION")
#Como consultar el tipo de dato
print(type("soy un dato str"))#Tipo'str'
print(type(5)) #Tipo 'int'
print(type(1.5))#Tipo 'float'
print(type(3+1)) #Tipo 'complex'
print(type(True)) #Tipo 'bool'
print(type(print("Mi cadena de texto"))) #Tipo'NoneType'